### ISSUE TITLE
NativeModules.RNReactNativeZlib is undefined. Make sure the library is linked on the native side.

### ISSUE THREAD

**Issue by tomlobato** [klarna/react-native-zlib#6]
No matter how I install (through react-native link or manually), i get this.
<img width="402" alt="Screen Shot 2019-12-08 at 20 20 42" src="https://user-images.githubusercontent.com/1187704/70398267-4a753300-19f8-11ea-9e56-93457f1a9ad2.png">
RNReactNativeZlib.xcodeproj  and libRNReactNativeZlib.a are both in Libraries and Build phases.
Any hint?

**Comment by OleksandrKucherenko** [comment]
It's android only implementation. iOS is not included into it.

**Comment by tomlobato** [comment]
Making it clear in the readme would be a great thing, or making the repo private to not waste people time!

**Comment by OleksandrKucherenko** [comment]
> Making it clear in the readme would be a great thing,

any PRs are welcome

**Comment by OleksandrKucherenko** [comment]
zlib on ios is natively implemented in JS engine. In android, it doesn't. That is why this module exists.
